blank_issues_enabled: false
contact_links:
  - name: 🌎 Website & Blog
    url: https://dsanchezcr.com
    about: Read my blog, explore my projects, and learn more about me.
  - name: 💼 LinkedIn
    url: https://linkedin.com/in/dsanchezcr
    about: Connect with me professionally.
  - name: 📬 Newsletter
    url: https://dsanchezcr.com/newsletter
    about: Subscribe to get my latest posts and updates.
